// Synthetic renderer fixtures generated by the production simulation.
import {writeFileSync} from 'node:fs';
import {Fixture, sphere} from '../../packages/combat-simulation/tests/fixtures.js';
function scenario(id: string) {
 const f = new Fixture();
 if(id !== 'hit') f.body.b=[sphere([3, 1, 0])];
 f.ready();
 const initial=f.simulation.snapshot();
 let sequence=0;
 const frames=[];
 for(let step=0;step<90;step++) {
  const extra=[];
  if(step===0) { if(id==='slow')extra.push(f.ability('slowField')); extra.push(f.fire('a',`replay-${id}`)); }
  const events=f.tick(extra);
  if(id==='cancel' && step===3)events.push(...f.simulation.setConnected('b',false));
  const snapshot=f.simulation.snapshot();
  const wrapped=events.map(event=>({v:1,matchId:snapshot.matchId,authorityEpoch:snapshot.authorityEpoch,frameEpoch:snapshot.frameEpoch,eventSequence:++sequence,tick:snapshot.tick,matchTimeMs:snapshot.matchTimeMs,event}));
  frames.push({atMs:snapshot.matchTimeMs,events:wrapped});
 }
 const terminals=frames.flatMap(x=>x.events).filter(x=>x.event.kind==='projectileTerminal');
 if(terminals.length!==1)throw new Error(`${id} requires exactly one terminal, got ${terminals.length}`);
 return {id, initial, initialEventSequence:0, frames};
}
const data={version:1,source:'CombatSimulation via its explicit synthetic Fixture; no network or device observations',scenarios:['hit','miss','slow','cancel'].map(scenario)};
writeFileSync(process.argv[2] ?? '/tmp/vkz-combat-replay.json', JSON.stringify(data));
console.log(JSON.stringify(data.scenarios.map(s=>({id:s.id,frames:s.frames.length,terminals:s.frames.flatMap(f=>f.events).filter(e=>e.event.kind==='projectileTerminal').map(e=>e.event.reason),segments:s.frames.flatMap(f=>f.events).filter(e=>e.event.kind==='projectileSegment').length}))));
