import { bytesToHex, randomBytes } from "@noble/hashes/utils.js";
import { hashSecret } from "../../domain/session.js";

const SESSION_SECRET_BYTES = 32;
const MATCH_CODE_BYTES = 6;

/**
 * A match-scoped session secret is generated by the server, returned once to
 * its owner, and stored only as a digest.
 */
export function issueSessionSecret(): { secret: string; hash: string } {
  const secret = bytesToHex(randomBytes(SESSION_SECRET_BYTES));
  return { secret, hash: hashSecret(secret) };
}

export function matchCodeBytes(): Uint8Array {
  return randomBytes(MATCH_CODE_BYTES);
}
